### PR TITLE
Added some more algorithm

### PR DESCRIPTION
**Pull request by dev-manindepth**
Completed Rebase section. @SaumyaSingh1 
Now I will go for squash.
I am planning like in every algorithm I have just written brute force approach now I will add optimized more and will commit changes and will try to add more examples after that there will be three or four commits in the same file then I will squash them in one or two commit

Is my approach correct or not, just drop some suggestions

### CODE REVIEW

**Comment by saumya1singh** [comment]
Hi @dev-manindepth !
So right now in `algorithm` branch you have 2 commits.
You can try `squashing` these two into one ?
Simply `git rebase -i master`. 
Or if you want to add more commits surely you can try to make changes in the two files of `bubble` and `insertion`  & then squash all the 4 or 5 commits into 1 & I will merge the PR :)

**Review by saumya1singh — APPROVED** [review]

**Comment by dev-manindepth** [comment]
Hey @SaumyaSingh1  I have completed the squash part also changed some older commit message using the same ```git rebase -i``` command, kindly check
In last two days I learned a lot because I face a lot of trouble like my HEAD where detached, commits were diversed , conflict and may more issue, from last two days I am not sitting idle continuously reading docs and other stuff on the internet to resolve my query, finally, I today  resolved almost all my issues, but still, there are a lot of doubts revolving in mind

**Comment by dev-manindepth** [comment]
https://www.reddit.com/r/git/comments/6jzogp/why_am_i_force_pushing_after_a_rebase/
I read this article a lot of doubts resolved after reading this

**Review by saumya1singh — APPROVED** [review]

**Comment by saumya1singh** [comment]
Of course you will learn by practice only @dev-manindepth  :)

**Comment by saumya1singh** [comment]
write now we have total 5 commits, do you want to squash into 1 or should I merge the PR ?

**Comment by dev-manindepth** [comment]
I think u can merge the PR now because all those commits belong to different algorithms, so I don't want them all to squash into one

**Comment by saumya1singh** [comment]
Great 
Congratulations @dev-manindepth

**Pull request merged**
